name: build-ci
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: build

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Build runner container image
        run: |
          podman build . -t test-runner:latest
